# Generated by Django 3.0.2 on 2020-01-25 18:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_statement', models.CharField(blank=True, default='', max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='SurveyForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('form_name', models.CharField(blank=True, default=True, max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Response',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response', models.CharField(blank=True, default=True, max_length=250)),
                ('author', models.CharField(blank=True, default=True, max_length=250)),
                ('question', models.ForeignKey(blank=True, default=True, on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='survey.Question')),
            ],
        ),
        migrations.AddField(
            model_name='question',
            name='form',
            field=models.ForeignKey(blank=True, default=True, on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='survey.SurveyForm'),
        ),
    ]
