# Generated by Django 3.0.2 on 2020-01-25 18:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='form',
            field=models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='survey.SurveyForm'),
        ),
        migrations.AlterField(
            model_name='response',
            name='author',
            field=models.CharField(blank=True, default='', max_length=250),
        ),
        migrations.AlterField(
            model_name='response',
            name='question',
            field=models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='survey.Question'),
        ),
        migrations.AlterField(
            model_name='response',
            name='response',
            field=models.CharField(blank=True, default='', max_length=250),
        ),
        migrations.AlterField(
            model_name='surveyform',
            name='form_name',
            field=models.CharField(blank=True, default='', max_length=250),
        ),
    ]
