# Generated by Django 3.0.2 on 2020-01-28 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0005_surveyform_number_of_responses'),
    ]

    operations = [
        migrations.AlterField(
            model_name='surveyform',
            name='number_of_responses',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
