# Generated by Django 3.0.2 on 2020-01-28 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0007_auto_20200128_1842'),
    ]

    operations = [
        migrations.AddField(
            model_name='surveyform',
            name='author',
            field=models.CharField(blank=True, default='', max_length=250),
        ),
    ]
