# Generated by Django 3.0.2 on 2020-01-28 18:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0008_surveyform_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='surveyform',
            name='author',
        ),
        migrations.RemoveField(
            model_name='surveyform',
            name='number_of_responses',
        ),
        migrations.CreateModel(
            name='FormResponse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('respondant_name', models.CharField(blank=True, default='', max_length=250)),
                ('form', models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, related_name='formresponses', to='survey.SurveyForm')),
            ],
        ),
    ]
